### ISSUE TITLE
Motivation and Purpose

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/532-group11#1]
In a few sentences, provide motivation for why you are creating a dashboard. Who is your target audience, and what role are you embodying? What problem could your dashboard solve for the intended user? You can read the Project background section for some rough ideas. Be brief and clear.

**Comment by yhchen20** [comment]
Our role: Marketing Research Company

Target audience: Investment Corporation

Our customer plans to enter film business and do some investment. If we could understand the return of investment of movies in the past few years, it may help our customer to make investment decisions in the future. To address this challenge, we propose building a data visualization app that allows the investment managers to visually explore a dataset of movies to identify common factors. Our app will show the distribution of movie budget, revenue, profit and movie popularity by filtering different variables in order to compare factors that contribute to the trend of movies.
