### ISSUE TITLE
Milestone 2 - Peer Review 

### ISSUE THREAD

**Issue by lephanthuymai** [UBC-MDS/532-group11#28]
Hi Group 11!
I'm Mai from Group 12, I'm glad to have a chance to do a peer-review for your group's work.
My first impression is that the topic chosen is very interesting! The documents are well structured and written, the dashboard contains useful features, so congratulations to have a good outcome for your 2 first milestones!
Here are some feedback, hopefully, it can help to make your dashboard even more convenient to use:
- Add dashboard's title so that it can be displayed on the browser's tab name
- Vote average by genre: probably need to use a different chart such as histogram or density chart as it is hard for a normal user to read the current one
- Need to clearly arrange the panels in order of steps of actions
Hope this is helpful.
Best,
Mai Le on behalf of Group 12

**Comment by yaz-saleh** [comment]
Hi Mai!
Thank you for your feedback :)

Please [check out the dashboard](https://moveymoney.herokuapp.com/) now and see below for an update on your suggestions!

- Add dashboard's title so that it can be displayed on the browser's tab name
**Response**: This has been implemented

- Vote average by genre: probably need to use a different chart such as histogram or density chart as it is hard for a normal user to read the current one
**Response**: The heatmap has been reformatted to present a simpler and cleaner look

- Need to clearly arrange the panels in order of steps of actions
 **Response**: Various formatting options have been applied to make the overall usage simpler and more direct.

**Comment by lephanthuymai** [comment]
Hi Yazan and Team,
Thank you for considering my feedback, your new UI looks awesome!
All the best,
Mai
