### ISSUE TITLE
"Peer" feedback

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/532-group11#35]
Greeting grp 11, J Lambert here,

Thanks for putting together this dashboard, it is really quite useful in finding out I can maximize profits in my new movie company. I took your app for a spin and here are some thought (which you have seen before, but now you can reply to them officially so that you TAs sees it):

- Could the heatmap have square tiles? It often looks neater
- The two line plots also have the same categories so maybe they could be put next to each other and share a legend that updates both when clicked?
- The release year axis is not formatted as a date when selecting additional years for the line plot.
- The line plots are rather narrow so when selecting a longer year period they look very noisy, I wonder if they can smoothen using lowess or downsamples to always have ten points or something (though I don't think you have learnt time resampling yet...) Maybe just adjust the width to height ratio a bit.
    - Actually I think removing the "western" category from the default view could also help a lot since it is a bit all over the place whereas the others are more neat. But make sure that matches your usage scenario.
- Somewhere describe the dashboard data and makers (like small text on the bottom with link to the data set and code and who made it

**Comment by yaz-saleh** [comment]
Hello J Lambert! Thank you for the feedback. Please [check out the dashboard](https://moveymoney.herokuapp.com/) now and see below for an update on your suggestions!

- [x] Could the heatmap have square tiles? It often looks neater 
**Response:** Heatmap now has square tiles!

- [x] The two line plots also have the same categories so maybe they could be put next to each other and share a legend that updates both when clicked?
**Response:** Two line plots have been formatted to be on the same line and share an interactive legend.

- [x] The release year axis is not formatted as a date when selecting additional years for the line plot.
**Response:** Fixed

- [x] The line plots are rather narrow so when selecting a longer year period they look very noisy, I wonder if they can smoothen using lowess or downsamples to always have ten points or something (though I don't think you have learnt time resampling yet...) Maybe just adjust the width to height ratio a bit.
**Response:** LOESS has been implemented to smoothen the lineplots

- [x] Actually I think removing the "western" category from the default view could also help a lot since it is a bit all over the place whereas the others are more neat. But make sure that matches your usage scenario.
**Response:** The default categories were changed to represent a better usage scenario.

- [x] Somewhere describe the dashboard data and makers (like small text on the bottom with link to the data set and code and who made it
**Response:** Descriptions for each plot were added along with a footer describing the dataset and the project.

**Comment by joelostblom** [comment]
Fantastic! The restyled dashboard looks incredibly slick! I love the color choices, plot titles and small "learn more" buttons!

Could you include a screenshot or short screencast as a gif of the final app? I am using these for a gallery of all dashboards. Here is a gid screenshot you can use, but you might want to include a short screencast later since your dashboard has scrolling.

![movey-money-dashboard](https://user-images.githubusercontent.com/4560057/107137333-7ae88380-68c0-11eb-9089-de381b198d19.gif)
